import { useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext.jsx'
import AppSidebar from '../components/AppSidebar.jsx'
import EmptyState from '../components/EmptyState.jsx'
import AssessmentPage from './AssessmentPage.jsx'

const patientActions = ['Daily Check-in', 'Mental Health Assessment', 'Write Journal', 'View AI Insights', 'View Recommendations']
const therapistActions = ['View Patients', 'View Reports', 'Add Recommendation', 'Add Therapy Note']

function MetricCard({ label, value = '—', detail = 'No data yet' }) { return <article className="metric-card"><p>{label}</p><strong>{value}</strong><span>{detail}</span></article> }
function PlaceholderChart({ title, message }) { return <section className="panel chart-panel"><div className="panel-heading"><div><h2>{title}</h2><p>History will appear here once data is available.</p></div></div><div className="chart-empty"><div className="chart-grid" aria-hidden="true" /> <EmptyState title="No trend data yet" message={message} /></div></section> }
function QuickActions({ actions, onAssessment }) { return <section className="panel"><div className="panel-heading"><div><h2>Quick actions</h2><p>Helpful tools will become available as each feature is added.</p></div></div><div className="action-grid">{actions.map((action) => action === 'Mental Health Assessment' ? <button className="action-card enabled-action" key={action} onClick={onAssessment}><span className="action-icon" aria-hidden="true">+</span><span>{action}</span><small>Available now</small></button> : <button className="action-card" key={action} disabled><span className="action-icon" aria-hidden="true">+</span><span>{action}</span><small>Coming soon</small></button>)}</div></section> }

function PatientDashboard() {
  const { user } = useAuth(); const navigate = useNavigate(); const [latest, setLatest] = useState(null)
  useEffect(() => { fetch('http://127.0.0.1:8000/api/assessment/history', { headers: { Authorization: `Bearer ${sessionStorage.getItem('access_token')}` } }).then((response) => response.ok ? response.json() : []).then((items) => setLatest(items[0] || null)).catch(() => setLatest(null)) }, [])
  return <><section className="hero"><p className="eyebrow">Today’s space</p><h1>Welcome back, {user?.name?.split(' ')[0]}</h1><p>Small check-ins can help you notice what you need today. Be gentle with yourself.</p></section><section className="metric-grid"><MetricCard label="Mood" /><MetricCard label="Stress" /><MetricCard label="Energy" /><MetricCard label="Overall wellness" value={latest?.result_category || '—'} detail={latest ? `Latest score: ${latest.total_score} · ${new Date(latest.created_at).toLocaleDateString()}` : 'Complete your first assessment to begin tracking your wellness patterns.'} /></section><section className="assessment-summary panel"><div><h2>Latest assessment</h2><p>{latest ? `${latest.result_category} · Score ${latest.total_score} · ${new Date(latest.created_at).toLocaleDateString()}` : 'Complete your first assessment to begin tracking your wellness patterns.'}</p></div><button className="primary-button compact-button" onClick={() => navigate('/patient/assessment')}>Take Assessment</button></section><QuickActions actions={patientActions} onAssessment={() => navigate('/patient/assessment')} /><div className="dashboard-grid"><PlaceholderChart title="Mood trend" message="Complete your first daily check-in to see your trends." /><PlaceholderChart title="Stress & energy" message="Your stress and energy patterns will appear here." /></div><div className="dashboard-grid"><section className="panel"><h2>Recent activity</h2><EmptyState title="No activity yet" message="Check-ins, assessments, and journal entries will appear here." /></section><section className="panel"><h2>Recommendations</h2><EmptyState title="No recommendations yet" message="Recommendations will appear here when they are available." /></section><section className="panel"><h2>Upcoming therapy</h2><EmptyState title="No sessions scheduled" message="Your upcoming therapy sessions will appear here." /></section><section className="panel"><h2>Notifications</h2><EmptyState title="You’re all caught up" message="New notifications will appear here." /></section></div><aside className="safety-note"><strong>Important:</strong> AI insights are not a medical diagnosis. If you are in immediate danger or experiencing a crisis, contact a qualified mental health professional or local emergency service.</aside></>
}
function TherapistDashboard() {
  return <><section className="hero"><p className="eyebrow">Practice overview</p><h1>Welcome, {useAuth().user?.name}</h1><p>Specialization: <strong>Not provided yet</strong></p></section><section className="metric-grid"><MetricCard label="Total patients" /><MetricCard label="Active patients" /><MetricCard label="Recent assessments" /><MetricCard label="Patients needing attention" /></section><QuickActions actions={therapistActions} /><div className="dashboard-grid"><section className="panel span-two"><div className="panel-heading"><div><h2>Patient list</h2><p>Patient mood, assessments, and activity will be shown here when available.</p></div></div><EmptyState title="No patients to display" message="Patient records will appear here when they are connected to your practice." /></section><PlaceholderChart title="Patient progress overview" message="Progress patterns will appear once patient data is available." /></div><section className="panel"><h2>Recent patient activity</h2><EmptyState title="No recent activity" message="Patient assessments and check-ins will appear here when available." /></section></>
}

export default function DashboardPage({ role }) {
  const [menuOpen, setMenuOpen] = useState(false); const { user, logout } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const isDashboard = location.pathname === `/${role}` || location.pathname === `/${role}/`
  const handleLogout = () => { logout(); navigate('/login') }
  const isAssessment = role === 'patient' && location.pathname === '/patient/assessment'
  return <div className="app-shell"><AppSidebar role={role} isOpen={menuOpen} onClose={() => setMenuOpen(false)} onLogout={handleLogout} /><div className="content-area"><header className="topbar"><button className="menu-button" aria-label="Open navigation" onClick={() => setMenuOpen(true)}>☰</button><div><p className="topbar-kicker">{role === 'patient' ? 'Patient portal' : 'Therapist portal'}</p><span>{user?.email}</span></div><button className="topbar-logout" onClick={handleLogout}>Log out</button></header><main className="dashboard-content">{isAssessment ? <AssessmentPage /> : isDashboard ? role === 'patient' ? <PatientDashboard /> : <TherapistDashboard /> : <section className="panel feature-empty"><h1>{location.pathname.split('/').pop().replaceAll('-', ' ')}</h1><EmptyState title="This section is not available yet" message="It will be added in a later project step." /></section>}</main></div></div>
}
